---
- name: Install Apache on frontend servers
  hosts: frontend
  become: yes
  tasks:
    - name: Install Apache package
      ansible.builtin.package:
        name:
          - httpd        # Apache web server
            - mariadb-server  # Database server
            - php
            - git
            - wget
            - curl
            - unzip
            - vim
            - net-tools
            - telnet
        state: present
