---
- name: demo for loops
  hosts: frontend
  tasks:
    - name: print the names
      ansible.builtin.debug:
        msg: "hello {{ item }}"
        loop:
          - sam
          - siva
          - ram
